"""actguard Python SDK."""

from ._config import configure
from .budget import BudgetGuard
from .exceptions import (
    ActGuardError,
    BudgetExceededError,
    CircuitOpenError,
    DuplicateIdempotencyKey,
    GuardError,
    IdempotencyInProgress,
    IdempotencyOutcomeUnknown,
    InvalidIdempotentToolError,
    MaxAttemptsExceeded,
    MissingIdempotencyKeyError,
    MissingRuntimeContextError,
    RateLimitExceeded,
    ToolExecutionError,
    ToolGuardError,
    ToolTimeoutError,
)
from .run_context import RunContext, session
from .tools import (
    FAIL_ON_DEFAULT,
    FAIL_ON_INFRA_ONLY,
    FAIL_ON_STRICT,
    IGNORE_ON_DEFAULT,
    BlockRegex,
    FailureKind,
    RequireFact,
    Threshold,
    circuit_breaker,
    enforce,
    idempotent,
    max_attempts,
    prove,
    rate_limit,
    timeout,
    tool,
)
from .tools.timeout import shutdown

__version__ = "0.1.0"

__all__ = [
    "ActGuardError",
    "BlockRegex",
    "BudgetGuard",
    "BudgetExceededError",
    "CircuitOpenError",
    "configure",
    "circuit_breaker",
    "DuplicateIdempotencyKey",
    "enforce",
    "FAIL_ON_DEFAULT",
    "FAIL_ON_INFRA_ONLY",
    "FAIL_ON_STRICT",
    "FailureKind",
    "GuardError",
    "idempotent",
    "IdempotencyInProgress",
    "IdempotencyOutcomeUnknown",
    "IGNORE_ON_DEFAULT",
    "InvalidIdempotentToolError",
    "max_attempts",
    "MaxAttemptsExceeded",
    "MissingIdempotencyKeyError",
    "MissingRuntimeContextError",
    "prove",
    "rate_limit",
    "RateLimitExceeded",
    "RequireFact",
    "RunContext",
    "session",
    "shutdown",
    "Threshold",
    "timeout",
    "tool",
    "ToolExecutionError",
    "ToolGuardError",
    "ToolTimeoutError",
    "__version__",
]
